# Generated by Django 3.1.4 on 2020-12-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20201229_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='course_name',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> sec: <django.db.models.fields.CharField> (<django.db.models.fields.CharField>)', max_length=50),
        ),
    ]
