# Generated by Django 3.1.4 on 2021-01-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20210121_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
