# Generated by Django 3.1.4 on 2020-12-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_courseinstance_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='course_name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
