# Generated by Django 3.1.4 on 2021-01-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20201230_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_instances',
        ),
        migrations.AddField(
            model_name='student',
            name='course1',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
