# Generated by Django 3.1.4 on 2021-01-19 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course1',
        ),
    ]
