# Generated by Django 3.2 on 2021-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_courseinstance_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='professor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
