# Generated by Django 3.2 on 2021-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_auto_20210119_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='course_query',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='course_name',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
