# Generated by Django 3.1.4 on 2021-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20210113_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
