# Generated by Django 3.2 on 2021-01-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_auto_20210119_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='course_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
