# Generated by Django 3.2 on 2021-01-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_alter_courseinstance_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstance',
            name='location',
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
    ]
